### ISSUE TITLE
Question: how to annotate only on change files on PR?

### ISSUE THREAD

**Issue by miurahr** [kiancross/checkstyle-annotations-action#10]
I'd like to use it on the project recently adopt checkstyle in the project.
There are 400 of unresolved warnings because an integration manager of the project does not like style only change.

It is worth to integrate the checkstyle annotation action if it  show  only  warnings for changed files, or changed lines.

How to annotate only on changed one?

**Comment by miurahr** [comment]
I found only a small number of warnings of unchanged files are shown in PR page.
It would be OK.
ex. https://github.com/miurahr/omegat/pull/1/files

**Comment by kiancross** [comment]
GitHub will separate annotations for unchanged files under a separate heading titled `Unchanged files with check annotations`. You can just ignore these, as they aren't related to the changes made in that pull request.

If you want these warnings to completely disappear, you can either 1) fix the warnings or 2) disable any of the warnings you do not want to fix in the Checkstyle config.
